# Generated by Django 2.2.10 on 2020-06-05 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispermit', models.BooleanField(default=False, verbose_name='위치정보 허용동의')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegiProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=20, verbose_name='1. 펫 이름')),
                ('pet_type', models.CharField(max_length=20, verbose_name='2. 펫 종류')),
                ('pet_age', models.IntegerField(verbose_name='3. 펫 나이')),
                ('pet_gender', models.CharField(choices=[('남', '남'), ('여', '여'), ('중성', '중성')], default=True, max_length=2, verbose_name='성별')),
                ('pet_image', models.ImageField(default='null', upload_to='', verbose_name='4. 프로필 사진')),
                ('pet_intro', models.TextField(max_length=100, verbose_name='5. 소개')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
