# Generated by Django 2.2.10 on 2020-06-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200605_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiprofile',
            name='pet_gender',
            field=models.CharField(choices=[('남', '남'), ('여', '여'), ('중성', '중성')], max_length=2, null=True, verbose_name='4. 성별'),
        ),
        migrations.AlterField(
            model_name='regiprofile',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='5. 프로필 사진'),
        ),
        migrations.AlterField(
            model_name='regiprofile',
            name='pet_intro',
            field=models.TextField(max_length=100, null=True, verbose_name='6. 소개'),
        ),
    ]
